// <auto-generated />
using System;
using Lean8.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lean8.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lean8.Core.Entities.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IFCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("NoSnack")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("ProteinCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("SleepCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("WaterCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Workout")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("Lean8.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProteinTargetGrams")
                        .HasColumnType("integer");

                    b.Property<string>("SleepTime")
                        .HasColumnType("text");

                    b.Property<double>("TargetWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("WorkoutTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentWeight = 86.0,
                            HeightCm = 175.0,
                            Name = "Lean8 User",
                            ProteinTargetGrams = 120,
                            SleepTime = "22:00",
                            TargetWeight = 65.0,
                            WorkoutTime = "07:00"
                        });
                });

            modelBuilder.Entity("Lean8.Core.Entities.WeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("WeightLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = "2026-08-06",
                            Weight = 86.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
