import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

// Nilai gizi pendekatan per porsi (sumber: TKPI Kemenkes / FatSecret)
const FOODS = [
  // ==================== KARBOHIDRAT / NASI ====================
  { name: 'Nasi putih', serving: '1 centong (100g)', calories: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  { name: 'Nasi goreng', serving: '1 porsi', calories: 450, protein: 12, carbs: 60, fat: 17 },
  { name: 'Nasi uduk', serving: '1 porsi', calories: 400, protein: 6, carbs: 60, fat: 15 },
  { name: 'Nasi kuning', serving: '1 porsi', calories: 400, protein: 7, carbs: 62, fat: 13 },
  { name: 'Nasi padang komplit', serving: '1 porsi', calories: 650, protein: 25, carbs: 70, fat: 30 },
  { name: 'Nasi liwet', serving: '1 porsi', calories: 380, protein: 8, carbs: 58, fat: 12 },
  { name: 'Nasi campur Bali', serving: '1 porsi', calories: 550, protein: 22, carbs: 65, fat: 22 },
  { name: 'Nasi tim ayam', serving: '1 porsi', calories: 350, protein: 15, carbs: 50, fat: 9 },
  { name: 'Nasi kebuli', serving: '1 porsi', calories: 500, protein: 18, carbs: 65, fat: 18 },
  { name: 'Nasi bakar ayam', serving: '1 porsi', calories: 380, protein: 14, carbs: 55, fat: 12 },
  { name: 'Nasi jagung', serving: '1 porsi (100g)', calories: 120, protein: 3, carbs: 26, fat: 1 },
  { name: 'Nasi tumpeng', serving: '1 porsi', calories: 420, protein: 12, carbs: 60, fat: 14 },
  { name: 'Nasi pecel Madiun', serving: '1 porsi', calories: 380, protein: 10, carbs: 55, fat: 14 },
  { name: 'Lontong sayur', serving: '1 porsi', calories: 350, protein: 8, carbs: 45, fat: 15 },
  { name: 'Lontong', serving: '1 buah (100g)', calories: 130, protein: 2, carbs: 28, fat: 0.3 },
  { name: 'Ketupat', serving: '1 buah (100g)', calories: 130, protein: 2, carbs: 28, fat: 0.3 },
  { name: 'Ketupat sayur', serving: '1 porsi', calories: 350, protein: 8, carbs: 45, fat: 15 },
  { name: 'Papeda', serving: '1 porsi', calories: 180, protein: 1, carbs: 42, fat: 0.5 },
  { name: 'Bubur ayam', serving: '1 mangkuk', calories: 300, protein: 12, carbs: 40, fat: 9 },
  { name: 'Bubur kacang hijau', serving: '1 mangkuk', calories: 250, protein: 8, carbs: 42, fat: 6 },
  { name: 'Bubur sumsum', serving: '1 mangkuk', calories: 200, protein: 2, carbs: 40, fat: 4 },
  { name: 'Ketan putih', serving: '1 porsi (100g)', calories: 180, protein: 3, carbs: 40, fat: 0.5 },

  // ==================== MIE / KWETIAU ====================
  { name: 'Mie goreng', serving: '1 porsi', calories: 400, protein: 10, carbs: 55, fat: 15 },
  { name: 'Indomie goreng', serving: '1 bungkus', calories: 400, protein: 9, carbs: 52, fat: 17 },
  { name: 'Indomie kuah', serving: '1 bungkus', calories: 350, protein: 8, carbs: 48, fat: 14 },
  { name: 'Mie aceh', serving: '1 porsi', calories: 480, protein: 15, carbs: 60, fat: 18 },
  { name: 'Mie celor', serving: '1 porsi', calories: 420, protein: 14, carbs: 50, fat: 16 },
  { name: 'Kwetiau goreng', serving: '1 porsi', calories: 430, protein: 12, carbs: 58, fat: 16 },
  { name: 'Bihun goreng', serving: '1 porsi', calories: 380, protein: 8, carbs: 55, fat: 13 },

  // ==================== DAGING & UNGGAS ====================
  { name: 'Rendang daging', serving: '1 potong (50g)', calories: 190, protein: 12, carbs: 4, fat: 14 },
  { name: 'Sate ayam + bumbu kacang', serving: '10 tusuk', calories: 400, protein: 25, carbs: 15, fat: 27 },
  { name: 'Sate kambing', serving: '10 tusuk', calories: 450, protein: 25, carbs: 10, fat: 35 },
  { name: 'Sate padang', serving: '10 tusuk', calories: 380, protein: 22, carbs: 20, fat: 22 },
  { name: 'Ayam goreng', serving: '1 potong (100g)', calories: 260, protein: 27, carbs: 5, fat: 15 },
  { name: 'Ayam bakar', serving: '1 potong (100g)', calories: 220, protein: 28, carbs: 4, fat: 10 },
  { name: 'Ayam penyet', serving: '1 porsi', calories: 400, protein: 30, carbs: 15, fat: 24 },
  { name: 'Ayam betutu', serving: '1 potong (100g)', calories: 280, protein: 26, carbs: 5, fat: 17 },
  { name: 'Ayam taliwang', serving: '1 potong (100g)', calories: 260, protein: 27, carbs: 6, fat: 14 },
  { name: 'Ayam rica-rica', serving: '1 porsi (100g)', calories: 240, protein: 25, carbs: 6, fat: 13 },
  { name: 'Opor ayam', serving: '1 porsi', calories: 300, protein: 20, carbs: 8, fat: 21 },
  { name: 'Dada ayam rebus', serving: '100g', calories: 165, protein: 31, carbs: 0, fat: 3.6 },
  { name: 'Bebek goreng', serving: '1 potong (100g)', calories: 300, protein: 24, carbs: 4, fat: 21 },
  { name: 'Bebek betutu', serving: '1 potong (100g)', calories: 320, protein: 25, carbs: 5, fat: 22 },
  { name: 'Semur daging', serving: '1 porsi', calories: 280, protein: 18, carbs: 12, fat: 17 },
  { name: 'Gulai kambing', serving: '1 porsi', calories: 350, protein: 20, carbs: 8, fat: 26 },
  { name: 'Tongseng kambing', serving: '1 porsi', calories: 320, protein: 18, carbs: 12, fat: 22 },
  { name: 'Iga bakar', serving: '1 potong (100g)', calories: 320, protein: 22, carbs: 3, fat: 25 },
  { name: 'Sop iga', serving: '1 mangkuk', calories: 350, protein: 20, carbs: 10, fat: 25 },
  { name: 'Sop buntut', serving: '1 mangkuk', calories: 380, protein: 22, carbs: 10, fat: 27 },
  { name: 'Sop konro', serving: '1 mangkuk', calories: 400, protein: 22, carbs: 12, fat: 28 },
  { name: 'Empal gentong', serving: '1 mangkuk', calories: 380, protein: 20, carbs: 12, fat: 26 },
  { name: 'Empal gepuk', serving: '1 potong (80g)', calories: 250, protein: 18, carbs: 10, fat: 15 },
  { name: 'Dendeng balado', serving: '1 porsi (60g)', calories: 220, protein: 16, carbs: 8, fat: 14 },
  { name: 'Coto Makassar', serving: '1 mangkuk', calories: 350, protein: 20, carbs: 10, fat: 24 },

  // ==================== IKAN & SEAFOOD ====================
  { name: 'Ikan bakar', serving: '1 ekor (100g)', calories: 170, protein: 25, carbs: 0, fat: 7 },
  { name: 'Pepes ikan', serving: '1 bungkus', calories: 150, protein: 18, carbs: 4, fat: 7 },
  { name: 'Ikan asin goreng', serving: '1 potong (30g)', calories: 90, protein: 12, carbs: 0, fat: 4 },
  { name: 'Ikan patin bakar', serving: '1 potong (100g)', calories: 200, protein: 22, carbs: 0, fat: 12 },
  { name: 'Gulai ikan', serving: '1 porsi', calories: 250, protein: 20, carbs: 6, fat: 16 },
  { name: 'Pindang ikan', serving: '1 porsi', calories: 180, protein: 20, carbs: 5, fat: 8 },
  { name: 'Ikan kuah kuning', serving: '1 porsi', calories: 200, protein: 20, carbs: 6, fat: 10 },
  { name: 'Woku ikan', serving: '1 porsi', calories: 220, protein: 22, carbs: 8, fat: 11 },
  { name: 'Cakalang fufu (asap)', serving: '100g', calories: 200, protein: 30, carbs: 0, fat: 8 },
  { name: 'Cumi goreng tepung', serving: '1 porsi (100g)', calories: 280, protein: 15, carbs: 20, fat: 16 },
  { name: 'Udang goreng tepung', serving: '1 porsi (100g)', calories: 260, protein: 16, carbs: 18, fat: 14 },
  { name: 'Kepiting saus padang', serving: '1 porsi', calories: 300, protein: 22, carbs: 15, fat: 17 },

  // ==================== BERKUAH ====================
  { name: 'Bakso sapi', serving: '1 mangkuk', calories: 350, protein: 18, carbs: 40, fat: 12 },
  { name: 'Soto ayam', serving: '1 mangkuk', calories: 220, protein: 12, carbs: 15, fat: 12 },
  { name: 'Soto Betawi', serving: '1 mangkuk', calories: 400, protein: 18, carbs: 12, fat: 30 },
  { name: 'Rawon', serving: '1 mangkuk', calories: 350, protein: 18, carbs: 20, fat: 22 },
  { name: 'Rawon grombyang', serving: '1 mangkuk', calories: 370, protein: 18, carbs: 22, fat: 23 },
  { name: 'Sop ayam', serving: '1 mangkuk', calories: 150, protein: 10, carbs: 10, fat: 8 },
  { name: 'Sop kambing', serving: '1 mangkuk', calories: 320, protein: 18, carbs: 10, fat: 22 },
  { name: 'Sayur lodeh', serving: '1 mangkuk', calories: 150, protein: 4, carbs: 12, fat: 10 },
  { name: 'Sayur asem', serving: '1 mangkuk', calories: 50, protein: 2, carbs: 10, fat: 0.5 },
  { name: 'Sayur bening bayam', serving: '1 mangkuk', calories: 45, protein: 3, carbs: 7, fat: 0.5 },

  // ==================== SALAD / SAYUR ====================
  { name: 'Gado-gado', serving: '1 porsi', calories: 300, protein: 10, carbs: 25, fat: 18 },
  { name: 'Ketoprak', serving: '1 porsi', calories: 320, protein: 10, carbs: 40, fat: 14 },
  { name: 'Pecel', serving: '1 porsi', calories: 280, protein: 9, carbs: 25, fat: 16 },
  { name: 'Karedok', serving: '1 porsi', calories: 250, protein: 8, carbs: 22, fat: 15 },
  { name: 'Trancam', serving: '1 porsi', calories: 180, protein: 6, carbs: 15, fat: 11 },
  { name: 'Asinan sayur', serving: '1 porsi', calories: 150, protein: 3, carbs: 30, fat: 2 },
  { name: 'Rujak buah', serving: '1 porsi', calories: 200, protein: 2, carbs: 45, fat: 2 },
  { name: 'Urap sayuran', serving: '1 porsi', calories: 150, protein: 5, carbs: 12, fat: 10 },
  { name: 'Gudeg', serving: '1 porsi', calories: 300, protein: 8, carbs: 40, fat: 13 },
  { name: 'Tumis kangkung', serving: '1 porsi', calories: 90, protein: 3, carbs: 8, fat: 6 },
  { name: 'Tumis buncis', serving: '1 porsi', calories: 80, protein: 3, carbs: 8, fat: 5 },
  { name: 'Tumis tauge', serving: '1 porsi', calories: 70, protein: 3, carbs: 6, fat: 4 },
  { name: 'Oseng tempe', serving: '1 porsi', calories: 150, protein: 8, carbs: 10, fat: 9 },
  { name: 'Capcay', serving: '1 porsi', calories: 150, protein: 6, carbs: 12, fat: 9 },
  { name: 'Terong balado', serving: '1 porsi', calories: 120, protein: 2, carbs: 10, fat: 8 },
  { name: 'Sambal goreng ati', serving: '1 porsi', calories: 220, protein: 14, carbs: 8, fat: 15 },
  { name: 'Sambal goreng kentang', serving: '1 porsi', calories: 180, protein: 3, carbs: 20, fat: 10 },

  // ==================== TAHU TEMPE TELUR ====================
  { name: 'Tempe goreng', serving: '1 potong (25g)', calories: 80, protein: 5, carbs: 4, fat: 5 },
  { name: 'Tahu goreng', serving: '1 potong (50g)', calories: 90, protein: 5, carbs: 3, fat: 6 },
  { name: 'Tahu isi', serving: '1 buah', calories: 120, protein: 5, carbs: 12, fat: 6 },
  { name: 'Pepes tahu', serving: '1 bungkus', calories: 100, protein: 6, carbs: 5, fat: 6 },
  { name: 'Botok tempe', serving: '1 bungkus', calories: 130, protein: 7, carbs: 6, fat: 9 },
  { name: 'Telur rebus', serving: '1 butir', calories: 75, protein: 6, carbs: 0.6, fat: 5 },
  { name: 'Telur dadar', serving: '1 butir', calories: 110, protein: 6, carbs: 1, fat: 9 },
  { name: 'Perkedel kentang', serving: '1 buah', calories: 100, protein: 2, carbs: 12, fat: 5 },

  // ==================== PELENGKAP ====================
  { name: 'Kerupuk', serving: '1 buah', calories: 60, protein: 0.5, carbs: 8, fat: 3 },
  { name: 'Emping', serving: '10 keping', calories: 90, protein: 1, carbs: 10, fat: 5 },
  { name: 'Sambal', serving: '1 sdm', calories: 25, protein: 0.5, carbs: 5, fat: 1 },

  // ==================== JAJANAN / GORENGAN ====================
  { name: 'Pisang goreng', serving: '1 buah', calories: 150, protein: 2, carbs: 20, fat: 8 },
  { name: 'Bakwan / ote-ote', serving: '1 buah', calories: 130, protein: 3, carbs: 15, fat: 7 },
  { name: 'Cireng', serving: '3 buah', calories: 180, protein: 2, carbs: 25, fat: 8 },
  { name: 'Cilok', serving: '10 buah', calories: 200, protein: 4, carbs: 35, fat: 5 },
  { name: 'Combro', serving: '1 buah', calories: 160, protein: 3, carbs: 20, fat: 8 },
  { name: 'Misro', serving: '1 buah', calories: 150, protein: 1, carbs: 25, fat: 5 },
  { name: 'Martabak manis', serving: '1 potong', calories: 300, protein: 6, carbs: 40, fat: 14 },
  { name: 'Martabak telur', serving: '1 potong', calories: 350, protein: 12, carbs: 25, fat: 22 },
  { name: 'Risoles', serving: '1 buah', calories: 150, protein: 4, carbs: 15, fat: 8 },
  { name: 'Pastel', serving: '1 buah', calories: 150, protein: 4, carbs: 15, fat: 8 },
  { name: 'Lemper', serving: '1 buah', calories: 150, protein: 4, carbs: 22, fat: 6 },
  { name: 'Batagor', serving: '1 porsi', calories: 350, protein: 12, carbs: 35, fat: 18 },
  { name: 'Siomay', serving: '1 porsi', calories: 300, protein: 12, carbs: 30, fat: 14 },

  // ==================== KUE TRADISIONAL ====================
  { name: 'Klepon', serving: '3 butir', calories: 100, protein: 1, carbs: 20, fat: 2 },
  { name: 'Onde-onde', serving: '1 buah', calories: 150, protein: 3, carbs: 25, fat: 5 },
  { name: 'Kue lapis', serving: '1 potong', calories: 130, protein: 1, carbs: 25, fat: 3 },
  { name: 'Kue lumpur', serving: '1 buah', calories: 140, protein: 2, carbs: 20, fat: 6 },
  { name: 'Serabi', serving: '1 buah', calories: 120, protein: 2, carbs: 18, fat: 4 },
  { name: 'Kue cubit', serving: '3 buah', calories: 150, protein: 2, carbs: 22, fat: 6 },
  { name: 'Kue putu', serving: '2 buah', calories: 130, protein: 1, carbs: 25, fat: 3 },
  { name: 'Wajik', serving: '1 potong', calories: 140, protein: 1, carbs: 30, fat: 2 },
  { name: 'Dodol', serving: '2 potong', calories: 150, protein: 1, carbs: 32, fat: 2.5 },
  { name: 'Getuk', serving: '1 potong', calories: 120, protein: 1, carbs: 26, fat: 1.5 },
  { name: 'Rengginang', serving: '2 keping', calories: 100, protein: 1, carbs: 20, fat: 2 },
  { name: 'Keripik tempe', serving: '10 keping', calories: 150, protein: 6, carbs: 12, fat: 9 },
  { name: 'Bakpia', serving: '1 buah', calories: 100, protein: 2, carbs: 18, fat: 2.5 },
  { name: 'Nagasari', serving: '1 buah', calories: 130, protein: 1, carbs: 24, fat: 3 },
  { name: 'Bika ambon', serving: '1 potong', calories: 160, protein: 2, carbs: 25, fat: 6 },
  { name: 'Kue pukis', serving: '2 buah', calories: 140, protein: 2, carbs: 22, fat: 5 },
  { name: 'Kue talam', serving: '1 potong', calories: 130, protein: 1, carbs: 24, fat: 3 },

  // ==================== ROTI & SEREAL ====================
  { name: 'Roti bakar coklat', serving: '1 porsi', calories: 250, protein: 5, carbs: 35, fat: 10 },
  { name: 'Roti tawar', serving: '2 lembar', calories: 160, protein: 5, carbs: 30, fat: 2 },
  { name: 'Oatmeal', serving: '1 mangkuk', calories: 150, protein: 5, carbs: 27, fat: 3 },

  // ==================== MINUMAN ====================
  { name: 'Es teh manis', serving: '1 gelas', calories: 100, protein: 0, carbs: 25, fat: 0 },
  { name: 'Teh tawar', serving: '1 gelas', calories: 0, protein: 0, carbs: 0, fat: 0 },
  { name: 'Kopi hitam', serving: '1 cangkir', calories: 5, protein: 0, carbs: 1, fat: 0 },
  { name: 'Kopi susu gula aren', serving: '1 cup', calories: 230, protein: 3, carbs: 30, fat: 11 },
  { name: 'Es cendol / dawet', serving: '1 gelas', calories: 230, protein: 2, carbs: 45, fat: 6 },
  { name: 'Es campur', serving: '1 mangkuk', calories: 280, protein: 3, carbs: 50, fat: 8 },
  { name: 'Es doger', serving: '1 gelas', calories: 250, protein: 3, carbs: 45, fat: 7 },
  { name: 'Es kelapa muda', serving: '1 gelas', calories: 150, protein: 1, carbs: 30, fat: 3 },
  { name: 'Es pisang ijo', serving: '1 porsi', calories: 300, protein: 3, carbs: 55, fat: 8 },
  { name: 'Es teler', serving: '1 gelas', calories: 320, protein: 4, carbs: 55, fat: 10 },
  { name: 'Kolak pisang', serving: '1 mangkuk', calories: 250, protein: 2, carbs: 45, fat: 7 },
  { name: 'Wedang jahe', serving: '1 gelas', calories: 60, protein: 0, carbs: 15, fat: 0 },
  { name: 'Bandrek', serving: '1 gelas', calories: 90, protein: 0, carbs: 22, fat: 0 },
  { name: 'Sekoteng', serving: '1 mangkuk', calories: 180, protein: 2, carbs: 35, fat: 3 },
  { name: 'STMJ (susu telur madu jahe)', serving: '1 gelas', calories: 200, protein: 7, carbs: 25, fat: 8 },
  { name: 'Jus alpukat', serving: '1 gelas', calories: 280, protein: 3, carbs: 30, fat: 18 },
  { name: 'Jus mangga', serving: '1 gelas', calories: 150, protein: 1, carbs: 35, fat: 0.5 },
  { name: 'Air kelapa', serving: '1 gelas', calories: 45, protein: 0.5, carbs: 9, fat: 0 },
  { name: 'Susu kedelai', serving: '1 gelas', calories: 100, protein: 7, carbs: 8, fat: 4 },
  { name: 'Susu full cream', serving: '200ml', calories: 120, protein: 6, carbs: 9, fat: 7 },
  { name: 'Yogurt plain', serving: '100g', calories: 60, protein: 5, carbs: 5, fat: 3 },

  // ==================== BUAH ====================
  { name: 'Pisang', serving: '1 buah', calories: 105, protein: 1, carbs: 27, fat: 0.4 },
  { name: 'Apel', serving: '1 buah', calories: 95, protein: 0.5, carbs: 25, fat: 0.3 },
  { name: 'Jeruk', serving: '1 buah', calories: 60, protein: 1, carbs: 15, fat: 0.2 },
  { name: 'Semangka', serving: '1 potong', calories: 50, protein: 1, carbs: 12, fat: 0.2 },
  { name: 'Mangga', serving: '1 buah', calories: 150, protein: 1, carbs: 38, fat: 0.6 },
  { name: 'Nanas', serving: '1 potong (100g)', calories: 50, protein: 0.5, carbs: 13, fat: 0.1 },
  { name: 'Pepaya', serving: '1 potong (100g)', calories: 43, protein: 0.5, carbs: 11, fat: 0.3 },
  { name: 'Rambutan', serving: '5 buah', calories: 65, protein: 0.6, carbs: 16, fat: 0.2 },
  { name: 'Duku', serving: '10 buah', calories: 60, protein: 1, carbs: 13, fat: 0.2 },
  { name: 'Salak', serving: '3 buah', calories: 80, protein: 0.5, carbs: 20, fat: 0.3 },
  { name: 'Manggis', serving: '3 buah', calories: 90, protein: 0.5, carbs: 23, fat: 0.5 },
  { name: 'Durian', serving: '3 biji', calories: 200, protein: 2, carbs: 35, fat: 7 },
  { name: 'Alpukat', serving: '1/2 buah', calories: 160, protein: 2, carbs: 8, fat: 15 },
  { name: 'Jambu biji', serving: '1 buah', calories: 60, protein: 1, carbs: 14, fat: 0.5 },
  { name: 'Sirsak', serving: '1 potong (100g)', calories: 66, protein: 1, carbs: 16, fat: 0.3 },
  { name: 'Nangka', serving: '3 biji', calories: 90, protein: 1, carbs: 23, fat: 0.3 },
  { name: 'Belimbing', serving: '1 buah', calories: 30, protein: 1, carbs: 7, fat: 0.3 },
  { name: 'Sawo', serving: '1 buah', calories: 80, protein: 0.5, carbs: 20, fat: 1 },
  { name: 'Melon', serving: '1 potong (100g)', calories: 34, protein: 0.8, carbs: 8, fat: 0.2 },
]

async function main() {
  await prisma.foodItem.createMany({ data: FOODS, skipDuplicates: true })
  console.log(`✅ Seeded ${FOODS.length} makanan Indonesia`)
}
main().finally(() => prisma.$disconnect())